# Generated by Django 4.2.15 on 2025-02-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_number', models.CharField(max_length=50, unique=True)),
                ('holder_name', models.CharField(max_length=100)),
                ('valid_until', models.DateField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('event', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
