# Generated by Django 5.1.6 on 2025-02-17 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VerifyPass', '0002_gatepass_members_checkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('members', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='gatepass',
            name='members',
        ),
        migrations.AddField(
            model_name='gatepass',
            name='id_proof',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='gatepass', to='VerifyPass.event'),
            preserve_default=False,
        ),
    ]
