# Generated by Django 5.1.6 on 2025-02-17 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VerifyPass', '0003_event_remove_gatepass_members_gatepass_id_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_pass', to='VerifyPass.event'),
        ),
    ]
