# Generated by Django 5.1.6 on 2025-02-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VerifyPass', '0004_alter_gatepass_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='valid_until',
            field=models.DateField(default='2025-02-23'),
        ),
    ]
