# Generated by Django 5.1.6 on 2025-02-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VerifyPass', '0005_alter_gatepass_valid_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatepass',
            name='email',
        ),
        migrations.RemoveField(
            model_name='gatepass',
            name='name',
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(default='external', max_length=100),
        ),
    ]
