# Generated by Django 5.1.6 on 2025-02-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VerifyPass', '0006_remove_gatepass_email_remove_gatepass_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
