# Generated by Django 5.1.6 on 2025-02-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VerifyPass', '0007_alter_gatepass_holder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='roll_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
